version: '3'

services:
  i18n.api:
    image: i18n.api
    build:
      context: .
      dockerfile: i18n.API/Dockerfile
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    build:
      context: .
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "/home/dynamodblocal/data"]
    ports:
      - "8000:8000"
    networks:
      - back-tier
    volumes:
      - "dbdata:/home/dynamodblocal/data"

volumes:
  dbdata: