version: '3'

services:
  i18n.api:
    image: i18n.api
    build:
      context: .
      dockerfile: i18n.API/Dockerfile
    depends_on:
      - i18b.dynamodb
  i18b.dynamodb:
    image: i18n.dynamodb
    env_file:
      - env_file.env
    build:
      context: .
      dockerfile: i18n.DynamoDB/Dockerfile
    volumes:
      - "dbdata:/data"
volumes:
  dbdata: