version: '3'

services:
  i18n.api:
    image: i18n.api
    build:
      context: .
      dockerfile: i18n.API/Dockerfile
    depends_on:
      - i18b.dynamodb
  i18b.dynamodb:
    image: i18n.dynamodb
    build:
      context: .
      dockerfile: i18n.DynamoDB/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - back-tier
    volumes:
      - "dbdata:/data"

volumes:
  dbdata: